name:                can-i-haz
version:             0.3.1.0
github:              "0xd34df00d/can-i-haz"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019-2022 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Generic implementation of the Has and CoHas patterns
category:            Control

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/can-i-haz#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  can-i-haz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - can-i-haz
    - deepseq
    - hspec
    - HUnit
